FROM centos:7.7.1908

ENV TIME_ZOME Asia/Shanghai
ENV LANG=zh_CN.utf8

ADD run.sh /usr/local
COPY haproxy.cfg /usr/local/haproxy/etc/
RUN yum -y install gcc gcc-c++ make glibc glibc-devel pcre pcre-devel \
        openssl openssl-devel systemd-devel zip unzip zlib zlib-devel git rsyslog\
        && rm -rf /etc/localtime \
        && ln -sf /usr/share/zoneinfo/${TIME_ZOME} /etc/localtime \
        && yum -y install kde-l10n-Chinese \
        && yum -y reinstall glibc-common \
        && localedef -c -f UTF-8 -i zh_CN zh_CN.utf8 \
        && echo "LANG="zh_CN.utf8"" >  /etc/locale.conf \
        && source /etc/locale.conf \
        && yum clean all \
        && mkdir -p /usr/local/src/ \
        && cd /usr/local/src \
        && git clone --branch v2.4.0 https://github.com/haproxy/haproxy.git \
        && cd /usr/local/src/haproxy \
        && make ARCH=x86_64 TARGET=linux-glibc USE_OPENSSL=1 USE_ZLIB=1 \
        USE_SYSTEMD=1 USE_CPU_AFFINITY=1 PREFIX=/usr/local/haproxy \
        && make install PREFIX=/usr/local/haproxy \
        && cp haproxy /usr/sbin/ \
        && chmod 777 /usr/local/run.sh

EXPOSE 80 443
CMD ["/usr/local/run.sh"]

